export const questions = [
  {
    id: 1,
    question: "Who is known as the 'Master Blaster' in cricket?",
    options: [
      "Sachin Tendulkar",
      "Ricky Ponting",
      "Brian Lara",
      "Jacques Kallis",
    ],
    answer: "Sachin Tendulkar",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 2,
    question: "Which country won the ICC Cricket World Cup in 2019?",
    options: ["India", "Australia", "England", "New Zealand"],
    answer: "England",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 3,
    question:
      "What is the highest individual score by a batsman in Test cricket?",
    options: ["375", "400", "501", "400*"],
    answer: "400*",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 4,
    question:
      "What is the name of the trophy awarded to the winner of the Ashes series?",
    options: ["The Urn", "The Cup", "The Bowl", "The Shield"],
    answer: "The Urn",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 5,
    question: "Which cricket stadium is known as the 'Home of Cricket'?",
    options: [
      "Wankhede Stadium",
      "Lords Cricket Ground",
      "MCG",
      "Eden Gardens",
    ],
    answer: "Lords Cricket Ground",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 6,
    question:
      "Who was the first cricketer to score a double century in One Day Internationals?",
    options: [
      "Rohit Sharma",
      "Sachin Tendulkar",
      "Virender Sehwag",
      "Chris Gayle",
    ],
    answer: "Sachin Tendulkar",
    difficulty: "Easy",
    category: "Cricket",
  },
  {
    id: 7,
    question: "Who holds the record for the fastest century in Test cricket?",
    options: [
      "Viv Richards",
      "Brendon McCullum",
      "Chris Gayle",
      "David Warner",
    ],
    answer: "Brendon McCullum",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 8,
    question:
      "Which cricketer has scored the most international runs in his career?",
    options: ["Sachin Tendulkar", "Ricky Ponting", "Virat Kohli", "Brian Lara"],
    answer: "Sachin Tendulkar",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 9,
    question: "Who was the first bowler to take 800 Test wickets?",
    options: [
      "Shane Warne",
      "Muttiah Muralitharan",
      "Glenn McGrath",
      "Anil Kumble",
    ],
    answer: "Muttiah Muralitharan",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 10,
    question: "Which country won the ICC T20 World Cup in 2016?",
    options: ["England", "West Indies", "India", "Australia"],
    answer: "West Indies",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 11,
    question:
      "Who was the first Indian cricketer to take a hat-trick in Test cricket?",
    options: ["Harbhajan Singh", "Kapil Dev", "Jasprit Bumrah", "Irfan Pathan"],
    answer: "Harbhajan Singh",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 12,
    question:
      "Which bowler has taken the most wickets in a single Cricket World Cup tournament?",
    options: [
      "Glenn McGrath",
      "Wasim Akram",
      "Mitchell Starc",
      "Muttiah Muralitharan",
    ],
    answer: "Mitchell Starc",
    difficulty: "Medium",
    category: "Cricket",
  },
  {
    id: 13,
    question:
      "Who holds the record for the highest individual score in an innings in Test cricket?",
    options: ["Brian Lara", "Don Bradman", "Virender Sehwag", "Len Hutton"],
    answer: "Brian Lara",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 14,
    question: "What is the highest partnership for any wicket in Test cricket?",
    options: ["624", "576", "467", "415"],
    answer: "624",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 15,
    question: "Which cricketer has taken the most catches in Test cricket?",
    options: ["Rahul Dravid", "Jacques Kallis", "Mark Waugh", "Steve Waugh"],
    answer: "Rahul Dravid",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 16,
    question:
      "Who was the first bowler to take all 10 wickets in a Test innings?",
    options: [
      "Anil Kumble",
      "Jim Laker",
      "Shane Warne",
      "Muttiah Muralitharan",
    ],
    answer: "Jim Laker",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 17,
    question: "What is the highest successful run-chase in a Test match?",
    options: ["418", "455", "529", "404"],
    answer: "418",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 18,
    question:
      "Who was the first cricketer to score a century in all three formats of international cricket?",
    options: [
      "Chris Gayle",
      "Brendon McCullum",
      "Rohit Sharma",
      "Suresh Raina",
    ],
    answer: "Suresh Raina",
    difficulty: "Difficult",
    category: "Cricket",
  },
  {
    id: 19,
    question: "What is the capital city of France?",
    options: ["London", "Berlin", "Paris", "Rome"],
    answer: "Paris",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 20,
    question: "Who painted the Mona Lisa?",
    options: [
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Michelangelo",
    ],
    answer: "Leonardo da Vinci",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 21,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "NaCl", "O2"],
    answer: "H2O",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 22,
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: ["Mark Twain", "Harper Lee", "J.K. Rowling", "Ernest Hemingway"],
    answer: "Harper Lee",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 23,
    question: "What is the tallest mammal?",
    options: ["Elephant", "Giraffe", "Blue Whale", "Kangaroo"],
    answer: "Giraffe",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 24,
    question: "Who was the first man to walk on the moon?",
    options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],
    answer: "Neil Armstrong",
    difficulty: "Easy",
    category: "General nkowledge",
  },
  {
    id: 25,
    question: "What is the currency of Japan?",
    options: ["Yuan", "Euro", "Yen", "Dollar"],
    answer: "Yen",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 26,
    question: "What is the largest planet in the solar system?",
    options: ["Saturn", "Jupiter", "Neptune", "Mars"],
    answer: "Jupiter",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 27,
    question: "Who is the author of the 'Harry Potter' series?",
    options: ["J.R.R. Tolkien", "J.K. Rowling", "Stephen King", "C.S. Lewis"],
    answer: "J.K. Rowling",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 28,
    question: "What is the main ingredient in guacamole?",
    options: ["Tomato", "Onion", "Avocado", "Pineapple"],
    answer: "Avocado",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 29,
    question: "In which year did the Titanic sink?",
    options: ["1912", "1921", "1905", "1930"],
    answer: "1912",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 30,
    question: "Who composed the famous musical piece 'Für Elise'?",
    options: [
      "Ludwig van Beethoven",
      "Wolfgang Amadeus Mozart",
      "Johann Sebastian Bach",
      "Franz Schubert",
    ],
    answer: "Ludwig van Beethoven",
    difficulty: "Medium",
    category: "General nkowledge",
  },
  {
    id: 31,
    question: "What is the longest river in the world?",
    options: [
      "Amazon River",
      "Nile River",
      "Mississippi River",
      "Yangtze River",
    ],
    answer: "Nile River",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 32,
    question: "Who discovered penicillin?",
    options: [
      "Alexander Fleming",
      "Marie Curie",
      "Albert Einstein",
      "Isaac Newton",
    ],
    answer: "Alexander Fleming",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 33,
    question: "Which planet is known as the 'Red Planet'?",
    options: ["Mars", "Venus", "Mercury", "Jupiter"],
    answer: "Mars",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 34,
    question: "Who wrote the novel 'One Hundred Years of Solitude'?",
    options: [
      "Gabriel García Márquez",
      "F. Scott Fitzgerald",
      "Leo Tolstoy",
      "Franz Kafka",
    ],
    answer: "Gabriel García Márquez",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 35,
    question: "What is the smallest bone in the human body?",
    options: ["Stapes (in the ear)", "Femur", "Tibia", "Humerus"],
    answer: "Stapes (in the ear)",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 36,
    question: "Who painted the famous artwork 'The Starry Night'?",
    options: [
      "Pablo Picasso",
      "Vincent van Gogh",
      "Claude Monet",
      "Salvador Dalí",
    ],
    answer: "Vincent van Gogh",
    difficulty: "Difficult",
    category: "General nkowledge",
  },
  {
    id: 37,
    question: "What is the chemical symbol for gold?",
    options: ["Au", "Ag", "Pt", "Hg"],
    answer: "Au",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 38,
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    answer: "Mars",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 39,
    question: "What is the freezing point of water in degrees Celsius?",
    options: ["0°C", "100°C", "-100°C", "25°C"],
    answer: "0°C",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 40,
    question: "What is the smallest bone in the human body?",
    options: ["Femur", "Tibia", "Stapes", "Radius"],
    answer: "Stapes",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 41,
    question: "What causes the tides on Earth?",
    options: ["Gravity", "Wind", "Earth's rotation", "Solar flares"],
    answer: "Gravity",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 42,
    question: "What is the process by which plants make their own food?",
    options: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"],
    answer: "Photosynthesis",
    difficulty: "Easy",
    category: "Science",
  },
  {
    id: 43,
    question: "What is the atomic number of carbon?",
    options: ["5", "6", "7", "8"],
    answer: "6",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 44,
    question: "Who developed the theory of relativity?",
    options: [
      "Isaac Newton",
      "Albert Einstein",
      "Stephen Hawking",
      "Galileo Galilei",
    ],
    answer: "Albert Einstein",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 45,
    question: "What is the study of fossils called?",
    options: ["Paleontology", "Anthropology", "Archaeology", "Geology"],
    answer: "Paleontology",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 46,
    question: "What is the unit of electrical resistance?",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    answer: "Ohm",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 47,
    question:
      "What is the process by which a liquid turns into a gas at its boiling point?",
    options: ["Evaporation", "Condensation", "Sublimation", "Vaporization"],
    answer: "Vaporization",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 48,
    question: "What is the speed of light in a vacuum?",
    options: [
      "299,792,458 meters per second",
      "300,000,000 meters per second",
      "150,000,000 meters per second",
      "200,000,000 meters per second",
    ],
    answer: "299,792,458 meters per second",
    difficulty: "Medium",
    category: "Science",
  },
  {
    id: 49,
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "H2O", "CO2", "C6H12O6"],
    answer: "NaCl",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 50,
    question: "What is the largest organ of the human body?",
    options: ["Heart", "Liver", "Skin", "Brain"],
    answer: "Skin",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 51,
    question: "What is the primary component of natural gas?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: "Methane",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 52,
    question: "Which element has the highest melting point?",
    options: ["Carbon", "Tungsten", "Titanium", "Osmium"],
    answer: "Carbon",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 53,
    question: "What is the Heisenberg Uncertainty Principle?",
    options: [
      "Energy cannot be created or destroyed",
      "Electrons revolve around the nucleus in fixed orbits",
      "It is impossible to determine both the position and momentum of an electron simultaneously",
      "An object at rest will stay at rest unless acted upon by an external force",
    ],
    answer:
      "It is impossible to determine both the position and momentum of an electron simultaneously",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 54,
    question: "What is the study of the Earth's atmosphere and weather?",
    options: ["Geology", "Meteorology", "Astronomy", "Climatology"],
    answer: "Meteorology",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 55,
    question:
      "What is the chemical process by which plants convert light energy into chemical energy?",
    options: ["Respiration", "Combustion", "Photosynthesis", "Fermentation"],
    answer: "Photosynthesis",
    difficulty: "Difficult",
    category: "Science",
  },
  {
    id: 56,
    question: "Which team won the inaugural IPL season in 2008?",
    options: [
      "Mumbai Indians",
      "Chennai Super Kings",
      "Rajasthan Royals",
      "Kolkata Knight Riders",
    ],
    answer: "Rajasthan Royals",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 57,
    question: "Who is the highest run-scorer in the history of IPL?",
    options: ["Virat Kohli", "Rohit Sharma", "Suresh Raina", "Chris Gayle"],
    answer: "Virat Kohli",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 58,
    question: "Which team has won the most IPL titles?",
    options: [
      "Chennai Super Kings",
      "Mumbai Indians",
      "Kolkata Knight Riders",
      "Sunrisers Hyderabad",
    ],
    answer: "Chennai Super Kings",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 59,
    question: "Who is known as the 'Universe Boss' in the IPL?",
    options: ["Rohit Sharma", "MS Dhoni", "Virat Kohli", "Chris Gayle"],
    answer: "Chris Gayle",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 60,
    question: "Which player has taken the most wickets in a single IPL season?",
    options: [
      "Lasith Malinga",
      "Dwayne Bravo",
      "Imran Tahir",
      "Bhuvneshwar Kumar",
    ],
    answer: "Dwayne Bravo",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 61,
    question: "Who is the only bowler to take a hat-trick in the IPL final?",
    options: ["Lasith Malinga", "Sunil Narine", "Amit Mishra", "Dwayne Bravo"],
    answer: "Lasith Malinga",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 78,
    question:
      "Who captained the Kolkata Knight Riders to the IPL title in 2012?",
    options: [
      "Gautam Gambhir",
      "Sourav Ganguly",
      "Brendon McCullum",
      "Dinesh Karthik",
    ],
    answer: "Gautam Gambhir",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 79,
    question:
      "Which batsman has scored the most number of hundreds in the IPL?",
    options: [
      "David Warner",
      "Suresh Raina",
      "Brendon McCullum",
      "Chris Gayle",
    ],
    answer: "Chris Gayle",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 85,
    question:
      "Which of these IPL franchise was banned for two years?",
    options: [
      "Kolkata Knight Riders",
      "Sunrisers Hyderabad",
      "Chennai Super Kings",
      "Gujarat Lions",
    ],
    answer: "Chennai Super Kings",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 82,
    question: "Which two teams made their IPL debuts in 2011?",
    options: [
      "Gujarat Lions and and Rising Pune Supergiant",
      "Kochi Tuskers Kerala and Rising Pune Supergiant",
      "Sunrisers Hyderabad and Gujarat Lions",
      "Kochi Tuskers Kerala and Pune Warriors India",
    ],
    answer: "Kochi Tuskers Kerala and Pune Warriors India",
    difficulty: "Easy",
    category: "IPL",
  },
  {
    id: 62,
    question: "Who is the youngest player to score a century in the IPL?",
    options: ["Prithvi Shaw", "Sanju Samson", "Rishabh Pant", "Shubman Gill"],
    answer: "Rishabh Pant",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 63,
    question:
      "Which team holds the record for the highest team total in IPL history?",
    options: [
      "Kolkata Knight Riders",
      "Royal Challengers Bangalore",
      "Mumbai Indians",
      "Chennai Super Kings",
    ],
    answer: "Royal Challengers Bangalore",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 64,
    question:
      "Who is the only player to score 4 centuries in a season IPL history?",
    options: ["David Warner", "Virat Kohli", "Chris Gayle", "Shane Watson"],
    answer: "Virat Kohli",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 88,
    question:
      "Before 2020, in which year did a part of the IPL take place in the UAE?",
    options: ["2014", "2012", "2015", "2013"],
    answer: "Virat Kohli",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 65,
    question:
      "Which team has won the Fair Play Award the most times in IPL history?",
    options: [
      "Sunrisers Hyderabad",
      "Chennai Super Kings",
      "Mumbai Indians",
      "Kolkata Knight Riders",
    ],
    answer: "Chennai Super Kings",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 66,
    question: "Who was the first player to score 5000 runs in the IPL?",
    options: ["Rohit Sharma", "Suresh Raina", "Virat Kohli", "David Warner"],
    answer: "Suresh Raina",
    difficulty: "Medium",
    category: "IPL",
  },

  {
    id: 67,
    question:
      "Which player has won the Orange Cap the most times in IPL history?",
    options: ["Chris Gayle", "David Warner", "Virat Kohli", "Sunil Narine"],
    answer: "David Warner",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 76,
    question: "Why was the second season of the IPL moved to South Africa?",
    options: [
      "Financial Problems",
      "Weather issues",
      "Critical Diseases",
      "India's national elections",
    ],
    answer: "India's national elections",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 75,
    question: "Who was the second captain to lift IPL trophy?",
    options: ["Gautam Gambhir", "M.S. Dhoni", "Adam Gilchrist", "Shane Warne"],
    answer: "Adam Gilchrist",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 81,
    question: "Where was the first IPL match played?",
    options: ["Mumbai", "Bangalore", "Kolkata", "Delhi"],
    answer: "Bangalore",
    difficulty: "Medium",
    category: "IPL",
  },
  {
    id: 68,
    question: "Who has scored the fastest century in IPL history?",
    options: ["Chris Gayle", "AB de Villiers", "David Warner", "Yusuf Pathan"],
    answer: "Chris Gayle",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 69,
    question: "Which bowler has the best bowling figures in an IPL match?",
    options: ["Anil Kumble", "Adam Zampa", "Sohail Tanvir", "Alzarri Joseph"],
    answer: "Alzarri Joseph",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 70,
    question:
      "Who is the only player to win the Purple Cap three times in IPL history?",
    options: [
      "Lasith Malinga",
      "Sunil Narine",
      "Bhuvneshwar Kumar",
      "Dwayne Bravo",
    ],
    answer: "Bhuvneshwar Kumar",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 71,
    question: "Which team has won the most matches in a single IPL season?",
    options: [
      "Chennai Super Kings",
      "Mumbai Indians",
      "Kolkata Knight Riders",
      "Sunrisers Hyderabad",
    ],
    answer: "Mumbai Indians",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 72,
    question: "Who is the only bowler to take two hat-tricks in IPL history?",
    options: ["Amit Mishra", "Yuvraj Singh", "Sunil Narine", "Rashid Khan"],
    answer: "Amit Mishra",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 73,
    question: "which was the title sponser of first IPL season?",
    options: ["VIVO", "TATA", "DLF", "PEPSI"],
    answer: "DLF",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 84,
    question: "Which cricketer hit the winning runs for Rajasthan Royals in the 2008 IPL?",
    options: ["Shane Warne", "Sohail Tanvir", "Graeme Smith", "Yusuf Pathan"],
    answer: "Sohail Tanvir",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 80,
    question: "Who is the first Indian to score a hundred in the IPL?",
    options: [
      "Gautam Gambhir",
      "Manish Pandey",
      "Virender Sehwag",
      "Paul Valthaty",
    ],
    answer: "Manish Pandey",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 77,
    question:
      "Which Indian player was banned for the remainder of the 2008 IPL season for slapping a fellow Indian player?",
    options: [
      "Suresh Raina",
      "Harbhajan Singh",
      "S. Sreesanth",
      "Ravindra Jadeja",
    ],
    answer: "Harbhajan Singh",
    difficulty: "Difficult",
    category: "IPL",
  },
  {
    id: 74,
    question: "Which teams were involved in the IPL's first-ever super over?",
    options: [
      "Chennai Super Kings and Kings XI Punjab",
      "Mumbai Indians and Deccan Chargers",
      "Kolkata Knight Riders and Rajasthan Royals",
      "Royal Challengers Bangalore and Delhi Daredevils",
    ],
    answer: "Kolkata Knight Riders and Rajasthan Royals",
    difficulty: "Difficult",
    category: "IPL",
  },
];
